Issue/45
top-tier-ci-coders/karate pull request #46
Opened 2019-02-16 16:12 UTC by philippaornell

Add a test that increases branch coverage for matchJsonOrObject() function.

2019-02-17 08:48 UTC, mstniy commented on karate-core/src/test/java/com/intuit/karate/ScriptTest.java
> +        //assertTrue(Script.matchNamed(MatchType.EQUALS, "foo", null, "{ val: -1002.2000000000000 }", ctx).pass);
Are these the test cases that fail on Mac?

2019-02-17 08:57 UTC, philippaornell commented on karate-core/src/test/java/com/intuit/karate/ScriptTest.java
> +        //assertTrue(Script.matchNamed(MatchType.EQUALS, "foo", null, "{ val: -1002.2000000000000 }", ctx).pass);
Yes! Sorry that I pushed that. :( I get build failure when I have those. I don't know if it maybe has something to do with my java version? But I don't feel like I have the time to sit and debug that hehe

2019-02-18 14:02 UTC, mstniy requested changes
This needs to be changed so that it's merged to adhocCoverage. addCoverage will not be used anymore, and we have distributed its commits to either adhocCoverage or addTests

2019-02-18 15:29 UTC, philippaornell commented
Fixed by #62 #53

2019-02-18 15:29 UTC, closed without merging